In [113]:
import pandas as pd
header = ['loc', 'age', 'Income_level', 'car_cost', 'park&ride_cost', 'metro_cost', 'bus_cost', 'car_traveltime', 'park&ride_traveltime', 'metro_traveltime', 'bus_traveltime', 'decision']

df_car = pd.read_csv('project1-s1.csv', names=header)




df_car['Car_Cost_75%'] = df_car.car_cost * 0.75
df_car['car_traveltime_75%'] = df_car.car_traveltime * 0.75


df_car

,loc,age,Income_level,car_cost,park&ride_cost,metro_cost,bus_cost,car_traveltime,park&ride_traveltime,metro_traveltime,bus_traveltime,decision,Car_Cost_75%,car_traveltime_75%
0,14,34,2,50,80,15,10,32,40,60,45,metro,37.50,24.00
1,14,52,1,40,45,15,10,36,45,60,45,metro,30.00,27.00
2,14,50,2,35,40,15,10,21,34,55,40,park-and-ride,26.25,15.75
3,14,44,1,50,35,15,20,40,35,25,20,bus,37.50,30.00
4,14,61,1,30,18,15,10,16,34,50,34,bus,22.50,12.00
5,14,44,2,20,12,10,5,12,26,45,30,metro,15.00,9.00
6,14,27,3,45,55,15,10,26,35,50,40,park-and-ride,33.75,19.50
7,14,54,2,50,40,20,10,28,45,60,45,park-and-ride,37.50,21.00
8,14,43,3,40,22,10,5,22,36,55,36,car,30.00,16.50
9,14,61,3,40,22,10,5,23,38,60,38,metro,30.00,17.25
10,15,52,2,60,55,15,10,32,43,60,45,park-and-ride,45.00,24.00
11,15,37,2,60,65,20,15,33,48,65,48,park-and-ride,45.00,24.75
12,15,52,1,65,70,15,10,37,57,70,57,bus,48.75,27.75
13,17,20,3,55,45,20,25,60,55,40,35,car,41.25,45.00
14,15,46,2,45,55,15,10,25,40,55,40,metro,33.75,18.75
15,15,65,3,60,30,15,10,32,40,60,47,park-and-ride,45.00,24.00
16,15,61,1,30,20,5,10,55,25,30,35,bus,22.50,41.25
17,15,38,2,50,27,15,10,27,43,60,43,metro,37.50,20.25
18,15,34,3,35,19,10,5,18,28,45,28,park-and-ride,26.25,13.50
19,15,50,1,45,24,15,15,25,43,55,43,bus,33.75,18.75
20,15,51,3,40,22,10,10,24,39,55,39,car,30.00,18.00
21,15,55,3,55,45,15,15,24,36,55,40,car,41.25,18.00
22,16,67,1,30,17,10,5,15,34,50,34,bus,22.50,11.25
23,16,67,2,60,65,20,15,40,55,70,55,metro,45.00,30.00
24,16,43,3,40,22,15,15,23,40,55,40,metro,30.00,17.25
25,16,62,2,20,15,10,5,11,30,45,30,metro,15.00,8.25
26,16,36,2,60,31,15,10,33,52,70,55,bus,45.00,24.75
27,16,64,1,70,36,20,15,38,45,60,45,metro,52.50,28.50
28,16,56,2,40,23,10,5,24,25,45,30,car,30.00,18.00
29,16,33,3,40,21,10,5,21,32,50,32,car,30.00,15.75
30,16,65,3,65,35,20,15,37,57,65,57,park-and-ride,48.75,27.75
31,16,36,3,25,14,10,5,13,32,45,32,bus,18.75,9.75
32,16,63,1,40,22,10,5,24,34,60,34,car,30.00,18.00
33,16,43,2,40,22,10,5,22,40,55,40,metro,30.00,16.50
34,16,34,2,60,32,20,10,32,49,65,50,car,45.00,24.00
35,17,51,2,20,11,10,5,12,23,40,25,bus,15.00,9.00
36,17,39,1,35,19,15,10,19,30,50,35,metro,26.25,14.25
37,17,27,1,25,13,10,5,14,34,50,34,metro,18.75,10.50
38,17,26,2,55,28,15,10,31,45,60,45,metro,41.25,23.25
39,17,52,1,65,35,20,15,37,48,60,48,bus,48.75,27.75
40,17,49,2,30,17,13,10,18,32,45,32,car,22.50,13.50
41,17,44,2,60,32,20,15,32,44,55,44,car,45.00,24.00
42,17,38,3,20,10,10,5,12,31,45,31,car,15.00,9.00
43,17,56,2,40,20,10,5,23,43,55,43,metro,30.00,17.25
44,17,34,3,30,15,10,5,18,30,45,30,bus,22.50,13.50
45,17,49,2,65,35,20,15,36,55,70,55,park-and-ride,48.75,27.00
46,17,60,3,45,25,15,10,26,41,55,41,park-and-ride,33.75,19.50
47,17,48,1,60,32,15,10,35,54,70,54,bus,45.00,26.25
48,17,51,1,55,30,15,10,31,42,60,45,metro,41.25,23.25
49,17,28,2,50,28,20,15,29,46,60,46,metro,37.50,21.75

In [16]:
a= df_test_p1[(df_test_p1['decision'] == 'bus')  | (df_test_p1['Income_level'] == 1)]
a

,loc,age,Income_level,car_cost,park&ride_cost,metro_cost,bus_cost,car_traveltime,park&ride_traveltime,metro_traveltime,bus_traveltime,decision
3,14,44,1,50,35,15,15.00,40,35,25,15.00,bus
4,14,61,1,30,18,15,7.50,16,34,50,25.50,bus
12,15,52,1,65,70,15,7.50,37,57,70,42.75,bus
16,15,61,1,30,20,5,7.50,55,25,30,26.25,bus
19,15,50,1,45,24,15,11.25,25,43,55,32.25,bus
22,16,67,1,30,17,10,3.75,15,34,50,25.50,bus
26,16,36,2,60,31,15,7.50,33,52,70,41.25,bus
31,16,36,3,25,14,10,3.75,13,32,45,24.00,bus
32,16,63,1,40,22,10,3.75,24,34,60,25.50,car
35,17,51,2,20,11,10,3.75,12,23,40,18.75,bus
39,17,52,1,65,35,20,11.25,37,48,60,36.00,bus
44,17,34,3,30,15,10,3.75,18,30,45,22.50,bus
47,17,48,1,60,32,15,7.50,35,54,70,40.50,bus

In [110]:
header = ['loc', 'age', 'Income_level',
 ' car_cost', 'park&ride_cost', 'metro_cost',
  'bus_cost', 'car_traveltime',
   'park&ride_traveltime',
    'metro_traveltime', 'bus_traveltime', 'decision']

df_test_p1 =pd.read_csv('project1-s1.csv', names= header)

df_test_p1.bus_cost *= 0.75
df_test_p1.bus_traveltime *= 0.75




#a= df_test_p1[(df_test_p1['decision'] == 'bus')  | (df_test_p1['Income_level'] == 1)]

#if a.all:
#    df_test_p1.bus_cost *= 0.75
#    df_test_p1.bus_traveltime *= 0.75
#
#
#
#    selected_rows2 = a[a['Income_level']== 3]
#    row_num2 = [i for i in (selected_rows2.index)]
#    a.drop(row_num2, inplace=True)
#
#    selected_rows = a[a['decision']== 'metro']
#    row_num = [i for i in (selected_rows.index)]
#    a.drop(row_num, inplace=True)
#
#    selected_rows = a[a['decision']== 'car']
#    row_num = [i for i in (selected_rows.index)]
#    a.drop(row_num, inplace=True)
#
#    selected_rows2 = a[a['Income_level']== 2]
#    row_num2 = [i for i in (selected_rows2.index)]
#    a.drop(row_num2, inplace=True)
#    
#    try:
#        if a.size != 0:
#            a.drop(a.columns[[3,4,5,7,8,9]], axis=1, inplace=True)
#    except:
#        pass

a

    loc  age  Income_level  bus_cost  bus_traveltime decision
3    14   44             1        20              20      bus
4    14   61             1        10              34      bus
12   15   52             1        10              57      bus
16   15   61             1        10              35      bus
19   15   50             1        15              43      bus
22   16   67             1         5              34      bus
39   17   52             1        15              48      bus
47   17   48             1        10              54      bus